import { useQuery } from '@tanstack/react-query'; import { StyleSheet, View } from 'react-native';
import { AppIcon } from '@/components/ui/app-icon'; import { AppText } from '@/components/ui/app-text'; import { Badge } from '@/components/ui/badge'; import { Card } from '@/components/ui/card'; import { Illustration } from '@/components/ui/illustration'; import { AnimatedNumber } from '@/components/ui/motion'; import { ProgressBar } from '@/components/ui/progress-bar'; import { Reveal } from '@/components/ui/reveal'; import { Screen } from '@/components/ui/screen'; import { EmptyState, LoadingState } from '@/components/ui/states';
import { useChild } from '@/features/children/hooks'; import { calculateLevel, calculateProgressPercent } from '@/features/progress/progress-utils'; import { rewardsService } from '@/features/rewards/rewards-service'; import { queryKeys } from '@/services/api/query-keys'; import { useAppStore } from '@/stores/app-store'; import { colors, radius, spacing } from '@/theme/tokens';

export default function RewardsScreen() {
  const childId = useAppStore((state) => state.activeChildId); const { data: child } = useChild(childId); const { data, isLoading } = useQuery({ queryKey: childId ? queryKeys.rewards(childId) : ['rewards', 'disabled'], queryFn: () => rewardsService.get(childId!), enabled: Boolean(childId) });
  if (isLoading) return <LoadingState />; if (!child || !data) return <EmptyState />; const level = calculateLevel(child.xp);
  return <Screen mode="kids" contentStyle={styles.screen}><View style={styles.header}><AppText variant="micro" style={styles.label}>YOUR COLLECTION</AppText><AppText variant="display">Explorer rewards</AppText><AppText tone="muted">Every reward remembers a skill you practiced.</AppText></View><Card variant="hero" style={styles.crest}><View style={styles.crestIcon}><AppIcon name="rewards" size={42} color={colors.warning} /></View><View style={styles.crestCopy}><AppText variant="title" tone="inverse">Level {level} explorer</AppText><AnimatedNumber value={child.xp} suffix=" XP" variant="bodyStrong" style={styles.crestXp} /><ProgressBar value={calculateProgressPercent(child.xp)} label="Level progress" color={colors.kids.sun} /></View></Card>{data.unlockedIds.length === 0 ? <Reveal><Card variant="flat" style={styles.empty}><Illustration name="empty-rewards" accessibilityLabel="An empty rewards shelf ready for the first badge" /><AppText variant="heading" style={styles.center}>Your first badge is waiting</AppText><AppText tone="muted" style={styles.center}>Complete a mission and this shelf will start filling with memories.</AppText></Card></Reveal> : null}<View style={styles.sectionTitle}><AppText variant="heading">Adventure badges</AppText><AnimatedNumber value={data.unlockedIds.length} suffix={` of ${data.definitions.length} earned`} variant="bodyStrong" /></View><View style={styles.grid}>{data.definitions.map((definition, index) => <Reveal key={definition.id} delay={index * 35} style={styles.badge}><Badge title={definition.title.en} icon={definition.icon} unlocked={data.unlockedIds.includes(definition.id)} /></Reveal>)}</View></Screen>;
}

const styles = StyleSheet.create({ screen: { gap: spacing.xl }, header: { gap: spacing.sm }, label: { color: colors.kids.primary }, crest: { flexDirection: 'row', alignItems: 'center', gap: spacing.lg, backgroundColor: colors.kids.navy }, crestIcon: { width: 76, height: 76, borderRadius: radius.lg, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center' }, crestCopy: { flex: 1, gap: spacing.sm }, crestXp: { color: colors.kids.sun }, empty: { gap: spacing.sm, alignItems: 'center' }, center: { textAlign: 'center' }, sectionTitle: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', gap: spacing.md }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, badge: { width: '47%', flexGrow: 1 } });
